# Generated by Django 4.2.11 on 2026-04-06 13:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('icon', models.CharField(default='📦', max_length=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('base_reward_min', models.DecimalField(decimal_places=2, default=20, max_digits=6)),
                ('base_reward_max', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('min_trust_required', models.CharField(choices=[('new', 'All Runners'), ('trusted', 'Trusted + Elite Only'), ('elite', 'Elite Only')], default='new', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Task Category',
                'verbose_name_plural': 'Task Categories',
                'db_table': 'hs_task_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_number', models.CharField(editable=False, max_length=12, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('delivery_type', models.CharField(choices=[('standard', 'Standard Delivery'), ('urgent', 'Urgent (2x reward)')], default='standard', max_length=20)),
                ('pickup_location', models.CharField(max_length=200)),
                ('delivery_location', models.CharField(max_length=200)),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(5)])),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('runner_payout', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('requires_purchase', models.BooleanField(default=False)),
                ('purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('open', '🟢 Open'), ('accepted', '🔵 Accepted'), ('picked_up', '🟠 Picked Up'), ('delivered', '🟡 Delivered'), ('confirmed', '✅ Confirmed'), ('cancelled', '❌ Cancelled'), ('disputed', '⚠️ Disputed')], default='open', max_length=20)),
                ('is_escrow_locked', models.BooleanField(default=False)),
                ('task_image', models.ImageField(blank=True, null=True, upload_to='task_images/')),
                ('delivery_proof_image', models.ImageField(blank=True, null=True, upload_to='delivery_proof/')),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_tasks', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tasks.taskcategory')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posted_tasks', to=settings.AUTH_USER_MODEL)),
                ('runner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'hs_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='tasks.task')),
            ],
            options={
                'db_table': 'hs_ratings',
            },
        ),
    ]
